#! /bin/csh
#
#   source this file to start falcON.
#   You can override the root by presetting $falcON
#
#  set a reasonable $falcON if it's not present
#

# Overrides $FALCON with pfalcON directory: 
#if ($?FALCON == 0) then
    if($?NEMO == 0) error "neither FALCON nor NEMO known, cannot start falcON"
    setenv FALCON $NEMO/usr/pfalcON/falcON
    unsetenv FALCONLIB
#endif

echo FALCON set to $FALCON

source $FALCON/falcON.rc

# end

